### ISSUE TITLE
viewMode=all does not work in ols4 v1

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [TIBHannover/ols4#74]
**Describe the bug**
It seems ols4 v1 does not support viewMode for the jstree endpoint

**To Reproduce**
call: api/ontologies/chebi/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_75835/jstree?viewMode=All&siblings=true

**Expected behavior**
It should work as ols3: https://service.tib.eu/ts4tib/api/ontologies/chebi/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_75835/jstree?viewMode=All&siblings=true

In frontend --> go to this tree view and click on "Full Tree" button  https://terminology.tib.eu/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_75835

**Comment by Pooya-Oladazimi** [comment]
another issue is that jstree returns 500 for individuals
[http://ols4backend21.service.tib.eu:8080/api/ontologies/vibso/individuals/https%253A%252F%25[…]00-0002-2239-3955/jstree?viewMode=All&siblings=false](http://ols4backend21.service.tib.eu:8080/api/ontologies/vibso/individuals/https%253A%252F%252Forcid.org%252F0000-0002-2239-3955/jstree?viewMode=All&siblings=false)

might be related to this
ols3:
[https://service.tib.eu/ts4tib/api/ontologies/vibso/individuals/https%253A%252F%252Fo[…]rg%252F0000-0002-2239-3955/jstree?viewMode=All&siblings=false](https://service.tib.eu/ts4tib/api/ontologies/vibso/individuals/https%253A%252F%252Forcid.org%252F0000-0002-2239-3955/jstree?viewMode=All&siblings=false) (edited)

**Comment by giraygi** [comment]
@Pooya-Oladazimi @deepananbu It seems the jstrees are formulated differently in ols4:
This is our frontend with Pooya's initial example: https://terminology.tib.eu/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_33292&obsoletes=false&subtab=graph

And this is EBI's frontend with the same example: https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_33292

EBI's frontend creates the same output of jstree when "Show all siblings" checkbox is clicked on the tree tab. Once it is clicked, three more calls are executed as listed below:
- https://www.ebi.ac.uk/ols4/api/v2/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_33232/hierarchicalChildren?size=1000&lang=en&includeObsoleteEntities=undefined
- https://www.ebi.ac.uk/ols4/api/v2/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_50906/hierarchicalChildren?size=1000&lang=en&includeObsoleteEntities=undefined
- https://www.ebi.ac.uk/ols4/api/v2/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_33232/hierarchicalChildren?size=1000&lang=en&includeObsoleteEntities=undefined

Afterwards, the jstree becomes the same as our jstree. I think we may imitate their approach, rather than implementing this feature all over.

On the other hand, If you click on "has role" and "subClassOf" checkboxes in the graph tab of EBI's frontend, then you get the same graph. It would be nice if our frontend does the same.

**Comment by Pooya-Oladazimi** [comment]
@giraygi 

The result format for the tree API is not the same as ols3. This forces the client to completely change the way the tree data is rendered.

besides, there is type inconsistency in the v2 result which makes it not suitable, have a look at this: https://github.com/EBISPOT/ols4/issues/649#issuecomment-2064162078

**Comment by Pooya-Oladazimi** [comment]
@giraygi 

In general, it is recommended to avoid v2 as much as possible: https://github.com/EBISPOT/ols4/issues/649#issuecomment-2069199672

**Comment by giraygi** [comment]
> @giraygi
> 
> The result format for the tree API is not the same as ols3. This forces the client to completely change the way the tree data is rendered.
> 
> besides, there is type inconsistency in the v2 result which makes it not suitable, have a look at this: [EBISPOT#649 (comment)](https://github.com/EBISPOT/ols4/issues/649#issuecomment-2064162078)

There is a v1 AI for the alternative hierarchicalChildren endpoints that they use. Here are the examples:

- https://www.ebi.ac.uk/ols4/api/ontologies/chebi/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_33232/hierarchicalChildren?size=1000&lang=en&includeObsoleteEntities=undefined
- https://www.ebi.ac.uk/ols4/api/ontologies/chebi/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_50906/hierarchicalChildren?size=1000&lang=en&includeObsoleteEntities=undefined
- https://www.ebi.ac.uk/ols4/api/ontologies/chebi/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_33232/hierarchicalChildren?size=1000&lang=en&includeObsoleteEntities=undefined

**Comment by Pooya-Oladazimi** [comment]
@deepananbu @giraygi 

As tested, works for class trees but it seems not implemented for property tree
